import type { DungeonDef, MonsterDef } from '../types/dungeon.js';

export const MONSTER_DEFS: Record<string, MonsterDef> = {
  forest_wolf: {
    id: 'forest_wolf',
    name: 'Forest Wolf',
    hp: 60,
    damage: 8,
    armor: 2,
    speed: 4,
    aggroRange: 10,
    attackRange: 2,
    attackCooldown: 1.2,
    xpReward: 25,
    lootTableId: 'forest_wolf_loot',
    model: 'wolf',
    abilities: [
      {
        id: 'wolf_bite',
        name: 'Savage Bite',
        type: 'melee',
        damage: 10,
        range: 2,
        cooldown: 8,
        statusEffect: { type: 'bleed', damage: 3, duration: 6, tickRate: 2 },
      },
    ],
  },
  forest_spider: {
    id: 'forest_spider',
    name: 'Giant Spider',
    hp: 40,
    damage: 12,
    armor: 1,
    speed: 5,
    aggroRange: 8,
    attackRange: 1.5,
    attackCooldown: 0.8,
    xpReward: 20,
    lootTableId: 'forest_spider_loot',
    model: 'spider',
    abilities: [
      {
        id: 'spider_venom',
        name: 'Venomous Bite',
        type: 'melee',
        damage: 8,
        range: 1.5,
        cooldown: 10,
        statusEffect: { type: 'poison', damage: 4, duration: 8, tickRate: 2 },
      },
    ],
  },
  forest_treant: {
    id: 'forest_treant',
    name: 'Ancient Treant',
    hp: 300,
    damage: 25,
    armor: 10,
    speed: 2,
    aggroRange: 12,
    attackRange: 3,
    attackCooldown: 2.0,
    xpReward: 100,
    lootTableId: 'forest_treant_loot',
    model: 'treant',
    isBoss: true,
    abilities: [
      {
        id: 'treant_ground_slam',
        name: 'Ground Slam',
        type: 'aoe',
        damage: 15,
        range: 6,
        cooldown: 12,
      },
      {
        id: 'treant_root_trap',
        name: 'Root Trap',
        type: 'debuff',
        damage: 0,
        range: 10,
        cooldown: 15,
        statusEffect: { type: 'root', damage: 0, duration: 3, tickRate: 0 },
      },
      {
        id: 'treant_summon_saplings',
        name: 'Summon Saplings',
        type: 'summon',
        damage: 0,
        range: 0,
        cooldown: 20,
      },
    ],
    phases: [
      { phase: 0, hpThreshold: 1.0, damageMultiplier: 1.0, speedMultiplier: 1.0, armorMultiplier: 1.0, abilities: ['treant_ground_slam'] },
      { phase: 1, hpThreshold: 0.6, damageMultiplier: 1.3, speedMultiplier: 1.2, armorMultiplier: 1.0, abilities: ['treant_ground_slam', 'treant_root_trap'] },
      { phase: 2, hpThreshold: 0.25, damageMultiplier: 1.6, speedMultiplier: 1.5, armorMultiplier: 1.0, abilities: ['treant_ground_slam', 'treant_root_trap', 'treant_summon_saplings'] },
    ],
  },
  forest_shaman: {
    id: 'forest_shaman',
    name: 'Forest Shaman',
    hp: 50,
    damage: 6,
    armor: 3,
    speed: 3,
    aggroRange: 12,
    attackRange: 10,
    attackCooldown: 2.5,
    xpReward: 35,
    lootTableId: 'forest_shaman_loot',
    model: 'shaman',
    abilities: [
      {
        id: 'shaman_bolt',
        name: 'Nature Bolt',
        type: 'ranged',
        damage: 14,
        range: 10,
        cooldown: 2.5,
        projectileSpeed: 8,
      },
      {
        id: 'shaman_poison_cloud',
        name: 'Poison Cloud',
        type: 'aoe',
        damage: 5,
        range: 5,
        cooldown: 12,
        statusEffect: { type: 'poison', damage: 4, duration: 8, tickRate: 2 },
      },
    ],
  },
  forest_sapling: {
    id: 'forest_sapling',
    name: 'Forest Sapling',
    hp: 25,
    damage: 5,
    armor: 0,
    speed: 4,
    aggroRange: 10,
    attackRange: 1.5,
    attackCooldown: 1.0,
    xpReward: 10,
    lootTableId: 'forest_wolf_loot',
    model: 'sapling',
  },
};

export const FOREST_DUNGEON: DungeonDef = {
  id: 'forest',
  name: 'Dark Forest',
  description: 'A twisted forest filled with dangerous creatures.',
  maxPlayers: 4,
  recommendedLevel: 1,
  rooms: [
    {
      id: 'forest_entrance',
      floorName: 'Entrance',
      spawns: [
        { monsterId: 'forest_wolf', position: { x: 5, y: 0, z: 5 }, respawnTime: 30 },
        { monsterId: 'forest_wolf', position: { x: -5, y: 0, z: 8 }, respawnTime: 30 },
      ],
      connections: ['forest_clearing'],
    },
    {
      id: 'forest_clearing',
      floorName: 'Clearing',
      spawns: [
        { monsterId: 'forest_spider', position: { x: 3, y: 0, z: 0 }, respawnTime: 30 },
        { monsterId: 'forest_spider', position: { x: -3, y: 0, z: 2 }, respawnTime: 30 },
        { monsterId: 'forest_wolf', position: { x: 0, y: 0, z: -5 }, respawnTime: 30 },
      ],
      connections: ['forest_entrance', 'forest_depths'],
    },
    {
      id: 'forest_depths',
      floorName: 'Depths',
      spawns: [
        { monsterId: 'forest_spider', position: { x: 4, y: 0, z: 4 }, respawnTime: 45 },
        { monsterId: 'forest_wolf', position: { x: -4, y: 0, z: 4 }, respawnTime: 45 },
        { monsterId: 'forest_wolf', position: { x: 0, y: 0, z: -3 }, respawnTime: 45 },
      ],
      connections: ['forest_clearing', 'forest_shaman_hollow'],
    },
    {
      id: 'forest_shaman_hollow',
      floorName: 'Shaman Hollow',
      spawns: [
        { monsterId: 'forest_shaman', position: { x: 5, y: 0, z: 3 }, respawnTime: 45 },
        { monsterId: 'forest_shaman', position: { x: -5, y: 0, z: 3 }, respawnTime: 45 },
        { monsterId: 'forest_wolf', position: { x: 0, y: 0, z: -4 }, respawnTime: 45 },
      ],
      connections: ['forest_depths', 'forest_gauntlet'],
    },
    {
      id: 'forest_gauntlet',
      floorName: 'The Gauntlet',
      spawns: [
        { monsterId: 'forest_wolf', position: { x: -6, y: 0, z: 5 }, respawnTime: 60 },
        { monsterId: 'forest_spider', position: { x: 6, y: 0, z: 5 }, respawnTime: 60 },
        { monsterId: 'forest_shaman', position: { x: 0, y: 0, z: -2 }, respawnTime: 60 },
        { monsterId: 'forest_spider', position: { x: 0, y: 0, z: -7 }, respawnTime: 60 },
      ],
      connections: ['forest_shaman_hollow', 'forest_boss'],
    },
    {
      id: 'forest_boss',
      floorName: 'Heart of the Forest',
      spawns: [
        { monsterId: 'forest_treant', position: { x: 0, y: 0, z: 0 }, respawnTime: 0 },
      ],
      connections: ['forest_gauntlet'],
    },
  ],
  bossId: 'forest_treant',
};
