import type { ItemDef } from '../types/inventory.js';

export const ITEM_DEFS: Record<string, ItemDef> = {
  wooden_sword: {
    id: 'wooden_sword',
    name: 'Wooden Sword',
    type: 'weapon',
    slot: 'mainHand',
    tier: 1,
    rarity: 'common',
    baseDamage: 8,
    description: 'A basic wooden training sword.',
    icon: 'wooden_sword',
    model: 'wooden_sword',
  },
  iron_sword: {
    id: 'iron_sword',
    name: 'Iron Sword',
    type: 'weapon',
    slot: 'mainHand',
    tier: 2,
    rarity: 'uncommon',
    baseDamage: 15,
    description: 'A sturdy iron blade.',
    icon: 'iron_sword',
    model: 'iron_sword',
  },
  leather_cap: {
    id: 'leather_cap',
    name: 'Leather Cap',
    type: 'armor',
    slot: 'head',
    tier: 1,
    rarity: 'common',
    baseArmor: 3,
    description: 'Simple leather headgear.',
    icon: 'leather_cap',
  },
  leather_vest: {
    id: 'leather_vest',
    name: 'Leather Vest',
    type: 'armor',
    slot: 'chest',
    tier: 1,
    rarity: 'common',
    baseArmor: 8,
    description: 'A basic leather chest piece.',
    icon: 'leather_vest',
  },
  leather_pants: {
    id: 'leather_pants',
    name: 'Leather Pants',
    type: 'armor',
    slot: 'legs',
    tier: 1,
    rarity: 'common',
    baseArmor: 5,
    description: 'Simple leather leggings.',
    icon: 'leather_pants',
  },
  leather_boots: {
    id: 'leather_boots',
    name: 'Leather Boots',
    type: 'armor',
    slot: 'feet',
    tier: 1,
    rarity: 'common',
    baseArmor: 2,
    description: 'Basic leather footwear.',
    icon: 'leather_boots',
  },
  health_potion: {
    id: 'health_potion',
    name: 'Health Potion',
    type: 'consumable',
    tier: 1,
    rarity: 'common',
    description: 'Restores 50 HP.',
    icon: 'health_potion',
  },
  wood_scrap: {
    id: 'wood_scrap',
    name: 'Wood Scrap',
    type: 'material',
    tier: 1,
    rarity: 'common',
    description: 'A piece of wood from the forest.',
    icon: 'wood_scrap',
  },
  wolf_pelt: {
    id: 'wolf_pelt',
    name: 'Wolf Pelt',
    type: 'material',
    tier: 1,
    rarity: 'uncommon',
    description: 'A sturdy wolf hide.',
    icon: 'wolf_pelt',
  },
  iron_chainmail: {
    id: 'iron_chainmail',
    name: 'Iron Chainmail',
    type: 'armor',
    slot: 'chest',
    tier: 2,
    rarity: 'uncommon',
    baseArmor: 15,
    description: 'Interlocking iron rings provide solid protection.',
    icon: 'iron_chainmail',
  },
  forest_bow: {
    id: 'forest_bow',
    name: 'Forest Bow',
    type: 'weapon',
    slot: 'mainHand',
    tier: 2,
    rarity: 'rare',
    baseDamage: 12,
    description: 'A bow crafted from ancient forest wood.',
    icon: 'forest_bow',
    model: 'forest_bow',
  },
};
